name: Check git dependencies

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v4

    - name: Check git dependencies
      run: |
        .github/bin/check-git-dependencies
